/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
public static void main(String[] args) {
        int a = 5, b = 10;
        int sum = a + b;
        System.out.println("Sum = " + sum);
    }
}
